import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { BookCheck, Camera, ChartSpline, Orbit, Radar, ShieldAlert, Waypoints, Workflow, } from "lucide-react";
import { homepageStats, platformModules, tiers, trustLogos, useCases } from "../content/siteData";
const heroSignals = [
    { label: "Narrative graph", icon: Radar },
    { label: "Realtime camera", icon: Camera },
    { label: "Drone ISR", icon: Orbit },
];
const tierIcons = {
    "tier-a": ShieldAlert,
    "tier-b": Camera,
    "tier-c": Orbit,
};
const moduleIcons = [Workflow, Camera, ChartSpline, Orbit, BookCheck, Waypoints];
const caseIcons = [ShieldAlert, Camera, Orbit, Waypoints];
export default function HomePage({ onNavigate }) {
    return (_jsxs(_Fragment, { children: [_jsx("section", { className: "hero-band hero-home", children: _jsxs("div", { className: "container hero-grid", children: [_jsxs("div", { className: "hero-content", children: [_jsx("p", { className: "kicker", children: "NOXIS / Tiered Strategic Surveillance Platform" }), _jsx("h1", { className: "display-title", children: "Know the Threat Surface" }), _jsx("p", { className: "hero-copy", children: "NOXIS combines narrative intelligence, realtime camera operations, and drone ISR into one accountable command stack." }), _jsx("div", { className: "hero-kpis", "aria-label": "Core capabilities", children: heroSignals.map((signal) => {
                                        const Icon = signal.icon;
                                        return (_jsxs("span", { className: "hero-kpi", children: [_jsx(Icon, { size: 16, "aria-hidden": "true" }), signal.label] }, signal.label));
                                    }) }), _jsxs("div", { className: "hero-actions", children: [_jsx("a", { href: "/pricing#contact", className: "pill-cta", onClick: (event) => {
                                                event.preventDefault();
                                                onNavigate("/pricing#contact");
                                            }, children: "Book a Demo" }), _jsx("a", { href: "/platform", className: "ghost-cta", onClick: (event) => {
                                                event.preventDefault();
                                                onNavigate("/platform");
                                            }, children: "Explore Platform" })] })] }), _jsxs("div", { className: "hero-visual", "aria-hidden": "true", children: [_jsx("img", { src: "/assets/noxis-hero.png", alt: "" }), _jsx("span", { className: "hero-visual__badge hero-visual__badge--top", children: "Tiered Command" }), _jsx("span", { className: "hero-visual__badge hero-visual__badge--bottom", children: "Rights and Oversight by Design" })] })] }) }), _jsx("section", { className: "section-block section-dark", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-head", children: [_jsx("p", { className: "kicker", children: "Trusted Network" }), _jsxs("h2", { className: "section-title section-title--with-icon", children: [_jsx(Radar, { className: "section-icon", "aria-hidden": "true" }), "Mission-critical organizations"] })] }), _jsx("div", { className: "logo-grid", children: trustLogos.map((logo) => (_jsxs("div", { className: "logo-cell", children: [_jsx("span", { className: "logo-cell__dot", "aria-hidden": "true" }), logo] }, logo))) })] }) }), _jsx("section", { id: "tiers", className: "section-block section-dark", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-head", children: [_jsx("p", { className: "kicker", children: "Tier Architecture" }), _jsxs("h2", { className: "section-title section-title--with-icon", children: [_jsx(Workflow, { className: "section-icon", "aria-hidden": "true" }), "One command surface, three operational layers"] })] }), _jsx("div", { className: "tier-grid", children: tiers.map((tier) => {
                                const Icon = tierIcons[tier.id] ?? ShieldAlert;
                                return (_jsxs("article", { className: "tier-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Icon, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: tier.name })] }), _jsx("h3", { children: tier.tagline }), _jsx("p", { children: tier.description }), _jsx("ul", { children: tier.capabilities.map((capability) => (_jsx("li", { children: capability }, capability))) })] }, tier.id));
                            }) })] }) }), _jsx("section", { className: "section-block section-dark stats-band", children: _jsx("div", { className: "container stats-grid", children: homepageStats.map((stat) => (_jsxs("article", { children: [_jsx("p", { className: "stat-value", children: stat.value }), _jsx("p", { className: "stat-label", children: stat.label })] }, stat.label))) }) }), _jsx("section", { className: "section-block section-dark", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-head", children: [_jsx("p", { className: "kicker", children: "Core Modules" }), _jsxs("h2", { className: "section-title section-title--with-icon", children: [_jsx(ChartSpline, { className: "section-icon", "aria-hidden": "true" }), "Constellation-grade components for high-risk operations"] })] }), _jsx("div", { className: "module-grid", children: platformModules.map((module, index) => {
                                const Icon = moduleIcons[index % moduleIcons.length];
                                return (_jsxs("article", { className: "module-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Icon, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: "Module" })] }), _jsx("h3", { children: module.title }), _jsx("p", { children: module.summary }), _jsx("ul", { children: module.bullets.map((bullet) => (_jsx("li", { children: bullet }, bullet))) })] }, module.title));
                            }) })] }) }), _jsx("section", { className: "section-block section-dark", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-head", children: [_jsx("p", { className: "kicker", children: "Use Cases" }), _jsxs("h2", { className: "section-title section-title--with-icon", children: [_jsx(Waypoints, { className: "section-icon", "aria-hidden": "true" }), "Built for narrative conflict, urban security, and ISR continuity"] })] }), _jsx("div", { className: "case-grid", children: useCases.map((entry, index) => {
                                const Icon = caseIcons[index % caseIcons.length];
                                return (_jsxs("article", { className: "case-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Icon, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: "Scenario" })] }), _jsx("h3", { children: entry.title }), _jsx("p", { children: entry.detail })] }, entry.title));
                            }) })] }) }), _jsx("section", { className: "cta-block", children: _jsxs("div", { className: "container cta-block__inner", children: [_jsxs("div", { children: [_jsx("p", { className: "kicker", children: "Command Briefing" }), _jsx("h2", { children: "Deploy NOXIS as a sovereign intelligence backbone." }), _jsx("p", { children: "Configure narrative, camera, and drone layers with mandate-specific governance controls." })] }), _jsx("a", { href: "/pricing#contact", className: "pill-cta", onClick: (event) => {
                                event.preventDefault();
                                onNavigate("/pricing#contact");
                            }, children: "Start Briefing" })] }) })] }));
}
