import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Camera, FileText, FlaskConical, Orbit, Radar, ShieldCheck, Sparkles } from "lucide-react";
import { labReports } from "../content/siteData";
const reportIcons = {
    "Narrative Intelligence": Radar,
    "Vision Operations": Camera,
    "Drone Operations": Orbit,
    Governance: ShieldCheck,
};
const labStats = [
    { value: "48h", label: "Typical alert cycle analysis" },
    { value: "3", label: "Research tracks" },
    { value: "Weekly", label: "Method and benchmark updates" },
];
export default function LabPage({ onNavigate }) {
    return (_jsxs(_Fragment, { children: [_jsx("section", { className: "hero-band hero-lab", children: _jsxs("div", { className: "container hero-grid", children: [_jsxs("div", { className: "hero-content", children: [_jsx("p", { className: "kicker", children: "LAB / Research and Intelligence Notes" }), _jsx("h1", { className: "display-title", children: "Operational intelligence reports for high-risk environments" }), _jsx("p", { className: "hero-copy", children: "NOXIS LAB publishes method notes, benchmark reports, and strategic briefs from narrative, vision, and aerial operations." }), _jsxs("div", { className: "hero-kpis", "aria-label": "Lab output", children: [_jsxs("span", { className: "hero-kpi", children: [_jsx(Radar, { size: 16, "aria-hidden": "true" }), "Narrative intelligence"] }), _jsxs("span", { className: "hero-kpi", children: [_jsx(Camera, { size: 16, "aria-hidden": "true" }), "Vision benchmarks"] }), _jsxs("span", { className: "hero-kpi", children: [_jsx(Orbit, { size: 16, "aria-hidden": "true" }), "ISR method notes"] })] })] }), _jsxs("div", { className: "hero-visual", "aria-hidden": "true", children: [_jsx("img", { src: "/assets/noxis-hero.png", alt: "" }), _jsx("span", { className: "hero-visual__badge hero-visual__badge--top", children: "Research-backed Operations" }), _jsx("span", { className: "hero-visual__badge hero-visual__badge--bottom", children: "Decision-grade Intelligence Notes" })] })] }) }), _jsx("section", { className: "section-block section-dark stats-band", children: _jsx("div", { className: "container stats-grid", children: labStats.map((stat) => (_jsxs("article", { children: [_jsx("p", { className: "stat-value", children: stat.value }), _jsx("p", { className: "stat-label", children: stat.label })] }, stat.label))) }) }), _jsx("section", { className: "section-block section-dark", children: _jsxs("div", { className: "container", children: [_jsxs("div", { className: "section-head", children: [_jsx("p", { className: "kicker", children: "Featured Reports" }), _jsxs("h2", { className: "section-title section-title--with-icon", children: [_jsx(FlaskConical, { className: "section-icon", "aria-hidden": "true" }), "Latest intelligence publications"] })] }), _jsx("div", { className: "case-grid", children: labReports.map((report) => {
                                const Icon = reportIcons[report.category] ?? FileText;
                                return (_jsxs("article", { className: "case-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Icon, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: report.category })] }), _jsx("h3", { children: report.title }), _jsx("p", { children: report.excerpt }), _jsx("a", { href: "/pricing#contact", className: "ghost-cta", onClick: (event) => {
                                                event.preventDefault();
                                                onNavigate("/pricing#contact");
                                            }, children: "Request Full Brief" })] }, report.title));
                            }) })] }) }), _jsx("section", { className: "section-block section-dark", children: _jsxs("div", { className: "container section-2col", children: [_jsxs("article", { className: "module-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Radar, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: "Research tracks" })] }), _jsxs("ul", { children: [_jsx("li", { children: "Narrative attack pattern intelligence" }), _jsx("li", { children: "Vision pipeline reliability and latency" }), _jsx("li", { children: "Drone ISR continuity and geospatial correlation" }), _jsx("li", { children: "Oversight, legal traceability, and institutional governance" })] })] }), _jsxs("article", { className: "module-card", children: [_jsxs("div", { className: "card-head", children: [_jsx("span", { className: "card-icon", "aria-hidden": "true", children: _jsx(Sparkles, { size: 18 }) }), _jsx("p", { className: "card-eyebrow", children: "Publication modes" })] }), _jsxs("ul", { children: [_jsx("li", { children: "Executive threat brief" }), _jsx("li", { children: "Operator methodology note" }), _jsx("li", { children: "System benchmark update" }), _jsx("li", { children: "Red-team observation memo" })] })] })] }) }), _jsx("section", { className: "cta-block", children: _jsxs("div", { className: "container cta-block__inner", children: [_jsxs("div", { children: [_jsx("p", { className: "kicker", children: "RAV3N Cell" }), _jsx("h2", { children: "Need a custom intelligence report for your mission profile?" }), _jsx("p", { children: "Our analysts can produce targeted briefings for policy, security, and command teams." })] }), _jsx("a", { href: "/pricing#contact", className: "pill-cta", onClick: (event) => {
                                event.preventDefault();
                                onNavigate("/pricing#contact");
                            }, children: "Request Custom Report" })] }) })] }));
}
