import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion, useMotionValue, useTransform } from "framer-motion";
import CountUp from "react-countup";
export default function Hero() {
    const mx = useMotionValue(0), my = useMotionValue(0);
    const tX = useTransform(mx, [-200, 200], [-8, 8]);
    const tY = useTransform(my, [-200, 200], [-6, 6]);
    return (_jsxs("div", { className: "grid gap-6 md:grid-cols-2 items-end", children: [_jsxs("div", { children: [_jsxs(motion.h1, { initial: { opacity: 0, y: 12 }, animate: { opacity: 1, y: 0 }, transition: { duration: .45 }, className: "text-4xl md:text-6xl font-extrabold leading-tight tracking-tight", children: ["AI against disinformation.", _jsx("br", {}), _jsx("span", { className: "text-accent", children: "Without mass surveillance." })] }), _jsx(motion.p, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: .08 }, className: "text-mute max-w-[760px] mt-3", children: "Rights-first intelligence. Synthetic signals, narrative graphs, audit-ready briefs. Never mass surveillance." }), _jsxs(motion.div, { initial: { opacity: 0, y: 8 }, animate: { opacity: 1, y: 0 }, transition: { delay: .12 }, className: "flex gap-3 mt-4", children: [_jsx("a", { className: "btn-primary", href: "#press", children: "Press & Media" }), _jsx("a", { className: "btn", href: "#about", children: "Learn More" })] }), _jsxs("div", { className: "grid gap-3 mt-5 md:grid-cols-3", children: [_jsx(motion.div, { whileHover: { y: -2 }, className: "panel shadow-glow-strong border-line/80", children: _jsxs("div", { className: "px-4 py-4", children: [_jsx("div", { className: "text-xs text-mute", children: "Signals/min" }), _jsx("div", { className: "text-2xl md:text-3xl font-extrabold", children: _jsx(CountUp, { end: 240, duration: 2 }) })] }) }), _jsx(motion.div, { whileHover: { y: -2 }, className: "panel shadow-glow-strong border-line/80", children: _jsxs("div", { className: "px-4 py-4", children: [_jsx("div", { className: "text-xs text-mute", children: "Narratives tracked" }), _jsx("div", { className: "text-2xl md:text-3xl font-extrabold", children: _jsx(CountUp, { end: 128, duration: 2 }) })] }) }), _jsx(motion.div, { whileHover: { y: -2 }, className: "panel shadow-glow-strong border-line/80", children: _jsxs("div", { className: "px-4 py-4", children: [_jsx("div", { className: "text-xs text-mute", children: "Codebase \u2022 Coffee (L)" }), _jsxs("div", { className: "text-2xl md:text-3xl font-extrabold", children: [_jsx(CountUp, { end: 1200000, duration: 2, separator: "," }), " \u2022 ", _jsx(CountUp, { end: 60, duration: 2 })] })] }) })] })] }), _jsxs(motion.div, { className: "h-[280px] md:h-[320px] rounded-2xl border border-line shadow-glow relative overflow-hidden", onMouseMove: (e) => {
                    const r = e.currentTarget.getBoundingClientRect();
                    mx.set(e.clientX - (r.left + r.width / 2));
                    my.set(e.clientY - (r.top + r.height / 2));
                }, initial: { opacity: 0, scale: .96 }, animate: { opacity: 1, scale: 1 }, transition: { duration: .45 }, style: { translateX: tX, translateY: tY }, children: [_jsx("div", { className: "absolute inset-0 bg-[radial-gradient(1100px_380px_at_-200px_-200px,#223355_10%,#1a2744_40%,#0d162c_70%)]" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-tr from-accent/10 via-transparent to-transparent" })] })] }));
}
