import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import HowViz from "../components/HowViz";
export default function How() {
    const [active, setActive] = useState(1);
    const variant = {
        initial: { opacity: 0, y: 10, filter: "blur(3px)" },
        animate: { opacity: 1, y: 0, filter: "blur(0px)", transition: { duration: 0.3 } },
        exit: { opacity: 0, y: -10, filter: "blur(2px)", transition: { duration: 0.2 } }
    };
    return (_jsx("section", { id: "how", className: "section", children: _jsxs("div", { className: "card p-6 md:p-8 max-w-[1200px] mx-auto", children: [_jsx("h2", { className: "m-0 text-2xl md:text-3xl font-bold mb-6", children: "How Noxis Works" }), _jsx("div", { className: "flex flex-wrap gap-2 mb-6", children: [1, 2, 3, 4, 5].map((s) => (_jsxs("button", { onClick: () => setActive(s), className: `px-3 py-1.5 rounded-xl border text-sm transition ${active === s
                            ? "border-accent2 text-ink shadow-glow-strong"
                            : "border-line text-mute hover:text-ink hover:shadow-glow"}`, children: [s === 1 && "1. Signals", s === 2 && "2. Analysis", s === 3 && "3. Graphs", s === 4 && "4. Decision Brief", s === 5 && "5. Audit Receipt"] }, s))) }), _jsxs("div", { className: "grid gap-4 md:grid-cols-2", children: [_jsx("div", { className: "rounded-2xl border border-line bg-panel p-4", children: _jsxs(AnimatePresence, { mode: "wait", children: [active === 1 && (_jsxs(motion.div, { ...variant, children: [_jsx("h3", { className: "font-semibold mb-2", children: "Signals" }), _jsxs("ul", { className: "text-mute list-disc list-inside space-y-1", children: [_jsx("li", { children: "Media, RSS, APIs" }), _jsx("li", { children: "Synthetic inputs" }), _jsx("li", { children: "Safety filters" })] })] }, "signals")), active === 2 && (_jsxs(motion.div, { ...variant, children: [_jsx("h3", { className: "font-semibold mb-2", children: "Analysis" }), _jsxs("ul", { className: "text-mute list-disc list-inside space-y-1", children: [_jsx("li", { children: "NLP clustering" }), _jsx("li", { children: "CV tags" }), _jsx("li", { children: "Anomaly detection" })] })] }, "analysis")), active === 3 && (_jsxs(motion.div, { ...variant, children: [_jsx("h3", { className: "font-semibold mb-2", children: "Graphs" }), _jsxs("ul", { className: "text-mute list-disc list-inside space-y-1", children: [_jsx("li", { children: "Narrative graph" }), _jsx("li", { children: "Actors & channels" }), _jsx("li", { children: "Propagation" })] })] }, "graphs")), active === 4 && (_jsxs(motion.div, { ...variant, children: [_jsx("h3", { className: "font-semibold mb-2", children: "Decision Brief" }), _jsxs("ul", { className: "text-mute list-disc list-inside space-y-1", children: [_jsx("li", { children: "Concise brief" }), _jsx("li", { children: "Evidence bundle" }), _jsx("li", { children: "Governance-aligned" })] })] }, "decision")), active === 5 && (_jsxs(motion.div, { ...variant, children: [_jsx("h3", { className: "font-semibold mb-2", children: "Audit Receipt" }), _jsxs("ul", { className: "text-mute list-disc list-inside space-y-1", children: [_jsx("li", { children: "Hash receipt" }), _jsx("li", { children: "Reproducible config" }), _jsx("li", { children: "Review trail" })] })] }, "audit"))] }) }), _jsx("div", { className: "rounded-2xl border border-line p-0 overflow-hidden", children: _jsx(HowViz, { step: active }) })] })] }) }));
}
